spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: 0408
    url: jdbc:postgresql://localhost:5432/ERP
    username: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
    show-sql: true