spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: 0408
    url: jdbc:postgresql://localhost:5432/ERP
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect